version: "3.7"
services:
  ai-agent-transcription:
    build:
      context: .
      dockerfile: Dockerfile
    image: ai-agent-transcription:latest # Defina o nome correto da imagem
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
